on:
  pull_request:
    branches: '*'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "some var: ${{vars.TF_ACTIONS_WORKING_DIR}}"
  # opentofu:
  #   uses: dnogu/ActionCI/.github/workflows/opentofu-plan.yaml@609855ed015a33f93405c27b7d08f413cc184e07
  #   secrets: inherit
  #   with:
  #     TF_ACTIONS_WORKING_DIR: ${{ vars.TF_ACTIONS_WORKING_DIR }}
  #     OPEN_TOFU_VER: ${{ vars.OPEN_TOFU_VER }}
